import { News } from '../types';

export const mockNews: News[] = [
  {
    id: '1',
    title: 'The Future of AI Technology',
    content: 'Artificial Intelligence continues to evolve at an unprecedented pace, transforming industries and creating new opportunities for innovation. Researchers are now focusing on developing more efficient and ethical AI systems.',
    image_url: 'https://images.unsplash.com/photo-1677442136019-21780ecad995',
    created_at: '2024-02-28T10:00:00Z',
    views: 1250,
    likes: 45,
    dislikes: 5,
    author_id: 'author1',
    tags: ['ai', 'technology'],
  },
  {
    id: '2',
    title: 'Sustainable Energy Breakthroughs',
    content: 'Recent developments in renewable energy technology have led to significant improvements in solar panel efficiency. Scientists have discovered new materials that could revolutionize how we harness solar power.',
    image_url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276',
    created_at: '2024-02-27T15:30:00Z',
    views: 980,
    likes: 32,
    dislikes: 3,
    author_id: 'author2',
    tags: ['electricity'],
  },
  {
    id: '3',
    title: 'Space Exploration Milestone',
    content: 'NASA announces new discoveries from the latest Mars rover mission. The findings suggest potential signs of ancient microbial life, opening new possibilities for understanding our solar system.',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa',
    created_at: '2024-02-26T09:15:00Z',
    views: 1500,
    likes: 67,
    dislikes: 8,
    author_id: 'author1',
    tags: ['space'],
  },
  {
    id: '4',
    title: 'Breakthrough in Quantum Computing',
    content: 'Scientists achieve quantum supremacy with a new processor design that can perform calculations in seconds that would take classical computers thousands of years.',
    image_url: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb',
    created_at: '2024-02-25T14:20:00Z',
    views: 2100,
    likes: 89,
    dislikes: 4,
    author_id: 'author2',
    tags: ['technology'],
  },
  {
    id: '5',
    title: 'Climate Change Solutions',
    content: 'Innovative carbon capture technology shows promising results in large-scale trials, offering new hope in the fight against climate change.',
    image_url: 'https://images.unsplash.com/photo-1421789665209-c9b2a435e3dc',
    created_at: '2024-02-24T11:45:00Z',
    views: 1750,
    likes: 56,
    dislikes: 7,
    author_id: 'author1',
    tags: ['weather'],
  },
  {
    id: '6',
    title: 'Medical Research Breakthrough',
    content: 'New treatment approach shows unprecedented success in early cancer detection and treatment, potentially revolutionizing oncology practices.',
    image_url: 'https://images.unsplash.com/photo-1576086213369-97a306d36557',
    created_at: '2024-02-23T16:30:00Z',
    views: 1890,
    likes: 78,
    dislikes: 5,
    author_id: 'author2',
    tags: ['medicine'],
  },
  {
    id: '7',
    title: 'Advances in Robotics',
    content: 'Latest developments in robotics showcase machines with enhanced dexterity and learning capabilities, opening new possibilities in manufacturing and healthcare.',
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e',
    created_at: '2024-02-22T13:15:00Z',
    views: 1670,
    likes: 45,
    dislikes: 6,
    author_id: 'author1',
    tags: ['technology'],
  },
  {
    id: '8',
    title: 'Ocean Conservation Success',
    content: 'Marine scientists report significant recovery in coral reef ecosystems following innovative restoration techniques and protection measures.',
    image_url: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0',
    created_at: '2024-02-21T09:40:00Z',
    views: 1450,
    likes: 92,
    dislikes: 3,
    author_id: 'author2',
    tags: ['marine'],
  },
  {
    id: '9',
    title: 'Future of Transportation',
    content: 'Revolutionary magnetic levitation technology promises to transform urban transportation with faster, more efficient, and environmentally friendly solutions.',
    image_url: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f',
    created_at: '2024-02-20T17:55:00Z',
    views: 1980,
    likes: 84,
    dislikes: 9,
    author_id: 'author1',
    tags: ['transportation'],
  }
];